server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    port: 6379
    host: 148.70.3.235
    password: asdasdnc2.
    database: 1
eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:8761/eureka
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    instance-id: ${spring.application.name}:${server.port}
ly:
  jwt:
    # 公钥地址
    pubKeyPath: E:/JWT/rsa/rsa.pub
    # cookie的名称
    cookieName: LY_TOKEN
