server:
  port: 8084
spring:
  application:
    name: page-service
  #关闭thymeleaf模板引擎的缓存
  thymeleaf:
    cache: false
    encoding: UTF-8
    prefix: classpath:/templates/
    suffix: .html
  rabbitmq:
    host: 148.70.3.235
    username: leyou
    password: leyou
    virtual-host: /leyou

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 #10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}

#静态化页面存放地址
ly:
  thymeleaf:
    destPath: E:\nginx-1.12.2\html\item