server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #服务注册地址
    #表示eureka client间隔多久去拉取服务器注册信息,默认为30秒
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api #添加路由前缀
  retryable: true #开启zuul的重试配置,需要 spring-retry 依赖
  routes:
    item-service: /item/**  #将商品微服务映射到/item/**
    search-service: /search/** #将搜索微服务映射到/search/**
    user-service: /user/** #将用户微服务映射到/user/**
    auth-service: /auth/** #将鉴权微服务映射到/auth/**
    cart-service: /cart/** #将购物车微服务映射到/cart/**
#  ignored-patterns: /upload/** #文件上传不经过zuul网关,减少负担

  #集合语法 - 代表可以配置多个
  ignored-services:
    #忽略upload-service服务,绕过zuul网关,减少网络负担
    - upload-service
  #携带请求本身自带的头信息
  add-host-header: true
  #设置 zuul的敏感头信息为空，否则 cookie 无效
  sensitive-headers:
ribbon:
  # Ribbon的连接超时时间
  ConnectTimeout: 60000
  # Ribbon的数据读取超时时间
  ReadTimeout: 60000
  # 是否对所有操作都进行重试
  OktoRetryOnAllOperations: true
  # 切换服务重连次数
  MaxAutoRetriesNextServer: 1
  # 同一服务重连次数
  MaxAutoRetries: 1

hystrix:
  command:
    default:
      execution:
        thread:
          # 熔断时间,超出则熔断
          timeoutInMilliseconds: 60000

ly:
  jwt:
    #公钥地址
    pubkeyPath: E:/JWT/rsa/rsa.pub
    #cookie名称
    cookieName: LY_TOKEN
  # 过滤器路径白名单
  filter:
    allowPaths:
      - /api/auth
      - /api/search
      - /api/user/register
      - /api/user/check
      - /api/user/send
      - /api/item








