server:
  port: 10086
spring:
  application:
    name: ly-eureka-register
eureka:
  client:
    fetch-registry: false
    register-with-eureka: false
    service-url:
      defalutZone: http://127.0.0.1:${server.port}/eureka
  server:
    enable-self-preservation: false #关闭自我保护
