server:
  port: 10010
spring:
  application:
    name: api-gateway
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka #服务注册地址
    registry-fetch-interval-seconds: 5
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
zuul:
  prefix: /api #添加路由前缀
  retryable: true #开启zuul的重试配置,需要 spring-retry 依赖
  routes:
    item-service: /item/**  #将商品微服务映射到/item/**
#  ignored-patterns: /upload/** #文件上传不经过zuul网关,减少负担
  ignored-services:
    #集合语法 - 代表可以配置多个
    - upload-service #忽略upload-service服务,绕过zuul网关,减少网络负担

ribbon:
  # Ribbon的连接超时时间
  ConnectTimeout: 60000
  # Ribbon的数据读取超时时间
  ReadTimeout: 60000
  # 是否对所有操作都进行重试
  OktoRetryOnAllOperations: true
  # 切换服务重连次数
  MaxAutoRetriesNextServer: 1
  # 同一服务重连次数
  MaxAutoRetries: 1

hystrix:
  command:
    default:
      execution:
        thread:
          # 熔断时间,超出则熔断
          timeoutInMilliseconds: 60000








